#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch rename legacy notebooks created by this skill to the new stable format."""

import os
import re
import sys

# --- VENV BOOTSTRAP ---
script_dir = os.path.dirname(os.path.abspath(__file__))
skill_root = os.path.dirname(script_dir)
venv_python = os.path.join(skill_root, ".venv", "bin", "python")

if os.path.exists(venv_python) and sys.executable != venv_python:
    os.execl(venv_python, venv_python, *sys.argv)
# ----------------------

sys.path.insert(0, script_dir)

from upload import list_notebooks, rename_notebook  # noqa: E402
from run import format_notebook_title  # noqa: E402


STANDARD_TITLE_RE = re.compile(r"^\[(CN|US|HK|CN_NAME)\]\s+.+\s+-\s+财报分析$")
LEGACY_DEEP_ANALYSIS_RE = re.compile(r"^(?P<name>.+?)\s*财务深度分析$")
CN_CODE_RE = re.compile(r"^(?P<code>\d{6})\s+(?P<name>.+)$")
HK_CODE_RE = re.compile(r"^HK_(?P<code>\d{5})(?:\s+(?P<name>.+))?$")
US_CODE_RE = re.compile(r"^(?P<code>[A-Z][A-Z0-9.\-]{0,9})$")


def resolve_cn_name(name: str) -> tuple[str, str] | None:
    """Resolve a CN company name to stock code and canonical short name."""
    try:
        from download import CnInfoDownloader

        downloader = CnInfoDownloader()
        resolved_stock_code, stock_info = downloader.find_stock(name)
        if resolved_stock_code:
            return resolved_stock_code, stock_info.get("zwjc", name).strip()
    except Exception:
        return None
    return None


def infer_market_code_name(title: str) -> tuple[str, str, str] | None:
    """Infer market/code/name from old notebook titles generated by this skill."""
    if not title or STANDARD_TITLE_RE.match(title):
        return None

    match = LEGACY_DEEP_ANALYSIS_RE.match(title.strip())
    if not match:
        return None

    raw_name = match.group("name").strip()

    cn_match = CN_CODE_RE.match(raw_name)
    if cn_match:
        return "CN", cn_match.group("code"), cn_match.group("name").strip()

    hk_match = HK_CODE_RE.match(raw_name)
    if hk_match:
        code = hk_match.group("code")
        name = (hk_match.group("name") or f"HK_{code}").strip()
        return "HK", code, name

    us_match = US_CODE_RE.match(raw_name.upper())
    if us_match:
        code = us_match.group("code").upper()
        return "US", code, code

    resolved_cn = resolve_cn_name(raw_name)
    if resolved_cn:
        code, canonical_name = resolved_cn
        return "CN", code, canonical_name

    return None


def main():
    ok, notebooks = list_notebooks()
    if not ok:
        print("❌ Failed to fetch notebook list from NotebookLM.")
        sys.exit(1)

    renamed = []
    skipped = []

    for notebook in notebooks:
        notebook_id = notebook.get("id")
        old_title = (notebook.get("title") or "").strip()
        inferred = infer_market_code_name(old_title)

        if not notebook_id or not old_title:
            continue

        if STANDARD_TITLE_RE.match(old_title):
            skipped.append((old_title, "already standardized"))
            continue

        if not inferred:
            skipped.append((old_title, "not recognized as a legacy skill title"))
            continue

        market, stock_code, stock_name = inferred
        new_title = format_notebook_title(market, stock_code, stock_name)
        if new_title == old_title:
            skipped.append((old_title, "already matches target title"))
            continue

        success, output = rename_notebook(notebook_id, new_title)
        if success:
            renamed.append((old_title, new_title, notebook_id))
        else:
            skipped.append((old_title, f"rename failed: {output.strip()}"))

    print(f"✅ Renamed notebooks: {len(renamed)}")
    for old_title, new_title, notebook_id in renamed:
        print(f"   {old_title} -> {new_title} ({notebook_id})")

    print(f"⏭️ Skipped notebooks: {len(skipped)}")
    for title, reason in skipped:
        print(f"   {title} [{reason}]")


if __name__ == "__main__":
    main()
